algoritmo "Produto"
// Função : apresentar o nome do protudo e diser o valor das parcelas sem juros
// Autor : Edgar Socrates
// Data : 08/03/2016
// Seção de Declarações 
var
nome: caracter
valor, prestacao: real
inicio
// Seção de Comandos
escreva("Informe nome do produto: ")
leia(nome)
escreva("Informe o valor do produto: ")
leia(valor)
prestacao<-valor/5
escreval("O valor de cada prestação a ser paga é:", prestacao)
fimalgoritmo
